webCV/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webCV.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

webCV/Controllers/studentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webCV.Controllers
{
    public class studentController : Controller
    {
        // GET: student
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult education()
        {
            return View();
        }
        public ActionResult projects()
        {
            return View();
        }
        public ActionResult reference()
        {
            return View();
        }
    }
}

webCV/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

webCV/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

webCV/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

webCV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sameen Abrar's CV", "Index", "student", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "student")</li>
                    <li>@Html.ActionLink("Education", "education", "student")</li>
                    <li>@Html.ActionLink("Projects", "projects", "student")</li>
                    <li>@Html.ActionLink("Reference", "reference", "student")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

webCV/Views/student/Index.cshtml
@{
    ViewBag.name = "Sameen Abrar";
    ViewBag.id = "20-41929-1";
    ViewBag.email = "sameenabrar13@gmail.com";
    ViewBag.contact = "01739274382";
}

<h2>Name: @ViewBag.name</h2>
<h2>ID: @ViewBag.id</h2>
<h2>Email: @ViewBag.email</h2>
<h2>Contact: @ViewBag.contact</h2>

webCV/Views/student/education.cshtml
@{
    ViewBag.Title = "Education";
    ViewBag.School = "DPS STS SCHOOL DHAKA";
    ViewBag.OlevelsGPA = "4.57";
    ViewBag.AlevelsGPA = "4.00";
    ViewBag.Schoolyear = "2019";

    ViewBag.university = "AIUB";
    ViewBag.bsc = "Computer Science and Engineering";
    ViewBag.semester = "9th Semester";
    ViewBag.cgpa = "3.83";


}

<div>
    <h2>@ViewBag.Title</h2>
    <ol>
        <li>
            School: @ViewBag.school
            <ul>
                <li>Board: Cambridge International Examinations</li>
                <li>
                    GPA:
                    <ul>
                        <li>O Levels: @ViewBag.OlevelsGPA</li>
                        <li>A Levels: @ViewBag.AlevelsGPA</li>
                    </ul>
                </li>
                <li>Graduation Year: @ViewBag.Schoolyear</li>
            </ul>
        </li>
        <li>
            University: @ViewBag.university
            <ul>
                <li>Bachelors: @ViewBag.bsc</li>
                <li>Semester: @ViewBag.semester</li>
                <li>CGPA: @ViewBag.cgpa</li>
            </ul>
        </li>
    </ol>
</div>

webCV/Views/student/projects.cshtml
@{
    ViewBag.Title = "Projects";

    ViewBag.oop1 = "ATM Machine";
    ViewBag.oop1des = "A console applicaiton that resembles how an ATM machine runs";

    ViewBag.oop2 = "Tourism Management System";
    ViewBag.oop2des = "A Desktop Application that allows tourists to plan trips and administration to manage trips";

    ViewBag.wt = "Crop Distribution System";
    ViewBag.wtdes = "A Web Application that provides a B2B crop distribution service";

}

<div>
    <h2>@ViewBag.Title</h2>

    <ol>
        <li>
            OOP1: @ViewBag.oop1
            <ul>
                <li>Description: @ViewBag.oop1des</li>
            </ul>
        </li>

        <li>
            OOP2: @ViewBag.oop2
            <ul>
                <li>Description: @ViewBag.oop2des</li>
            </ul>
        </li>

        <li>
            WebTech: @ViewBag.wt
            <ul>
                <li>Description: @ViewBag.wtdes</li>
            </ul>
        </li>

    </ol>
</div>

webCV/Views/student/reference.cshtml
@{
    ViewBag.Title = "Reference";

    ViewBag.refname = "Ayesha Akhtar";
    ViewBag.refemail = "ayesha.akhtar@gmail.com";
    ViewBag.refphone = "01748206945";

}

<h2>@ViewBag.Title</h2>
<ol>
    <li>
        Name: @ViewBag.refname
        <ul>
            <li>Email: @ViewBag.refemail</li>
            <li>Phone: @ViewBag.refphone</li>
        </ul>
    </li>
</ol>